---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: multiport
spec:
   replicas: 3
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
   selector:
     matchLabels:
        role: multiwebsite
   template:
     metadata:
       labels:
          role: multiwebsite
     spec:
       containers:
           - name: con1
             image: linuxkid/multiport-http:v2
             ports:
               - containerPort: 80
               - containerPort: 8080
               - containerPort: 8081
...
