---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim3
  labels:
    app: website
spec:
  storageClassName: slow2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 2Gi
...
