---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim2
  labels:
    app: website1
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 10Gi
...
