---
apiVersion: v1
kind: Pod
metadata:
    name: host
spec:
   containers:
      - name: con1
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: vol1
            mountPath: /mnt
   volumes:
      - name: vol1
        hostPath:
           path: /data
           type: DirectoryOrCreate
...
