apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-gcp
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: slow
    gcePersistentDisk:
      fsType: "ext4" 
      pdName: k8sdisk-1
