---
apiVersion: v1
kind: Pod
metadata:
   name: pd1
   labels:
     disktype: normal
spec:
   containers:
      - name: con1
        image: linuxkid/multiport-http:v3
        ports:
          - containerPort: 80
        volumeMounts:
          - name: pddisk1
            mountPath: /mnt
            subPath: abc
   volumes:
      - name: pddisk1
        persistentVolumeClaim:
           claimName: pv-claim1
...
