---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-redis
  namespace: bs-demo
  labels:
    env: dev
    role: nginx-redis
spec:
  containers:
     - name: con1
       image: nginx
       ports:
         - containerPort: 80
 
     - name: con2
       image: redis
       ports:
         - containerPort: 6379
...
