---
apiVersion: v1
kind: Service
metadata:
   name: deploy-svc1
spec:
   type: NodePort
   ports:
     - name: http-port
       port: 80
       targetPort: 80
       protocol: TCP
     - name: http-port-8080
       port: 8080
       targetPort: 8080
       protocol: TCP
     - name: http-port-8081
       port: 8081
       targetPort: 8081
       protocol: TCP
   selector:
       role: multiwebsite
...
