---
apiVersion: v1
kind: Service
metadata:
   name: expose-prometheus-grafana
   namespace: monitoring
spec:
   type: NodePort
   ports:
     - name: grafana
       port: 80
       targetPort: 3000
       nodePort: 30250
       protocol: TCP
   selector:
       app: kube-prometheus-grafana
...
