---
apiVersion: v1
kind: Service
metadata:
   name: expose--prometheus
   namespace: monitoring
spec:
   type: NodePort
   ports:
     - name: prometheus
       port: 9090
       targetPort: 9090
       nodePort: 30252
       protocol: TCP
   selector:
        app: prometheus
...
