---
apiVersion: v1
kind: Service
metadata:
   name: expose-prometheus-alertmanager
   namespace: monitoring
spec:
   type: NodePort
   ports:
     - name: prometheus-alertmanager
       port: 9093
       targetPort: 9093
       nodePort: 30251
       protocol: TCP
   selector:
           alertmanager: kube-prometheus
...
