---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
   name: apache-replica
   labels:
      role: apachereplica
spec:
   replicas: 2
   selector:
      matchLabels:
         role: apache2
   template:
      metadata:
         name: apache2pod
         labels:
           role: apache2
      spec:
         containers:
            - name: con1
              image: httpd
              ports:
                 - containerPort: 80
...
