---
apiVersion: v1
kind: LimitRange
metadata:
  name: custom-limit-range
  namespace: ops-playground
spec:
  limits:
  - default:
      memory: 200Mi
      cpu: 200m
    defaultRequest:
      memory: 50Mi
      cpu: 50m
    type: Container
...
