---
apiVersion: v1
kind: LimitRange
metadata:
  name: custom-limit-range
spec:
  limits:
  - default:
      memory: 200Mi
      cpu: 200m
    defaultRequest:
      memory: 50Mi
      cpu: 50m
    max:
      memory: 150Mi
      cpu: 150m
    min:
      memory: 50Mi
      cpu: 50m
   type: Container
   
...
