---
apiVersion: v1
kind: Pod
metadata:
    name: webserver2
    namespace: bs1
spec:
    containers:
       - name: con1
         image: nginx
         ports:
            - containerPort: 80
         resources:
            requests:
                cpu: 100m
                memory: 100Mi
            limits:
                cpu: 120m
                memory: 120Mi                
...
