---
apiVersion: v1
kind: Pod
metadata:
   name: mysqlserver
spec:
   containers:
     - name: con1
       image: mysql
       ports:
          - containerPort: 3306
       env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                    name: dblogin
                    key: password
   
...
